### ISSUE TITLE
No need for else here.

### ISSUE THREAD

**Issue by kchurikov** [maitraysuthar/rest-api-nodejs-mongodb#4]
https://github.com/maitraysuthar/rest-api-nodejs-mongodb/blob/f165fdfcd110ce0991ba56d9a6e8be9bf782e4c9/controllers/BookController.js#L29

**Comment by maitraysuthar** [comment]
Hi @kchurikov , As per normal scenario your thought is right, but while developing APIs we need to keep our responses consistent. 
```bash
if(books.length > 0){
	return apiResponse.successResponseWithData(res, "Operation success", books);
}else{
	return apiResponse.successResponseWithData(res, "Operation success", {});
}
```
Here `books` returns `object` when got data, and returns `null` in case not. Which makes response inconsistent. That's why I am returning a blank `object {}` in else condition. Due to this, API consumer don't need to check for `null` and he/she stays Happy :laughing: .

I hope your doubts got clear. Closing the issue.

**Comment by maitraysuthar** [comment]
I see, Sure. I will minify conditions from the next update. Thanks for the suggestions & your interest in the repo.
